// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xorfdhjzfealfxrdnnzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvcmZkaGp6ZmVhbGZ4cmRubnpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODE5MzMsImV4cCI6MjA3MDA1NzkzM30.Hy0nybUiiQxPTyg8u3JD4ylq5nCNT4XrbVt5PIGMDpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});